---
- hosts: 127.0.0.1
  remote_user: higor
  become: yes
  tasks:
    - name: "Executa o container MySQL"
      docker_container:
         name: dbglpi
         image: mysql:5.6
         env:
          MYSQL_ROOT_PASSWORD: dbglpi
    - name: "Executa o container GLPI"
      docker_container:
          name: glpi
          image: diouxx/glpi
          links:
            - "dbglpi:mysql"
          ports:
            - "80:80"
 